/* 
	500: DATABASE/SERVER ERROR

	404: NO RESOURCE FOUND IN URI (RESPONSE BODY DESCRIBE WHY)
	403: SERVER UNDERSTOOD THE REQUEST BUT REFUSE TO FULFILL IT (RESPONSE DESCRIBE WHY)

	400: SERVER DO NOT UNDERSTOOD THE REQUEST AND REFUSE TO CONTINUE (MALFORMED BODY REQUEST)
	
	422: SERVER UNDERSTOOD THE REQUEST AND SYNTAX IS CORRECT, BUT CANNOT PERFORM THE ACTION
	409: CANNOT PERFOM THE ACTION BECAUSE ITS CONFLICTED WITH AN RESOURCE ON THE SERVER

	200: WHEN THE PROCESS IS COMPLETED AND RETURNED AN OBJECT
	201: WHEN THE PROCESS IS COMPLETED BUT DO NOT RETURN AN OBJECT OR RETURN ONLY A REFERRER IN HEADER
	204: WHEN THE RESOURCE IS DELETED BUT DO NOT RETURN ANY RESPONSE
*/